name: unlam
version: '0.1.0.0'
synopsis: Lambda calculus toy
description: Please see README.md
category: Web
author: Bree Elle Gardner
maintainer: letsbreelhere@gmail.com
copyright: 2016 Bree Elle Gardner
license: PublicDomain
github: letsbreelhere/unlam

default-extensions:
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - FlexibleInstances
  - LambdaCase
  - PatternSynonyms
  - RankNTypes
  - TypeOperators

dependencies:
  - base >=4.7 && <5
  - haskeline
  - mtl
  - recursion-schemes

source-dirs:
  - app
  - src

ghc-options:
  - -Wall
  - -fno-warn-overlapping-patterns
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  pointkiller:
    main: PointKiller.hs
  eval-lam:
    main: Evaluator.hs

tests:
  unlam-test:
    main: Spec.hs
    source-dirs: test
